-- MySQL Script generated by MySQL Workbench
-- dom 22 out 2017 21:26:08 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema micro-cms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `micro-cms` ;

-- -----------------------------------------------------
-- Schema micro-cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micro-cms` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `micro-cms` ;

-- -----------------------------------------------------
-- Table `micro-cms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `micro-cms`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `micro-cms`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `micro-cms`.`user` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `micro-cms`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `micro-cms`.`post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `micro-cms`.`post` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(400) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `body` TEXT NOT NULL COMMENT '	',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `micro-cms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `path_UNIQUE` ON `micro-cms`.`post` (`path` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_post_user_idx` ON `micro-cms`.`post` (`user_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `micro-cms`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `micro-cms`;
INSERT INTO `micro-cms`.`user` (`id`, `name`, `password`, `created_at`, `updated_at`) VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', '2017-10-10 00:00:00', NULL);

COMMIT;

